-- Add 'present' column to User table
-- This marks which students are physically present at the conference

-- Step 1: Add the present column (defaults to false)
ALTER TABLE "User"
ADD COLUMN IF NOT EXISTS present BOOLEAN DEFAULT false;

-- Step 2: Mark all users as NOT present initially
UPDATE "User" SET present = false;

-- Step 3: Mark only the students who are present at the conference
UPDATE "User" SET present = true WHERE name IN (
  'Laura Gomez Cortes',
  'Emily Fisher',
  'Nitisha Bhatta',
  'Sri Vaishnavi Janapareddy',
  'Aria Puranik',
  'Veda Wachche',
  'Pitipanage Thisath Muhandheera',
  'Kaushal Kumar',
  'Kshitij Kumar',
  'Shravan Ramesh',
  'Hasita Reddy Kummeta',
  'Roseleen Kaur',
  'Dorothy Dhinakar',
  'Saanvi Dandu',
  'Olufemi Onasanya',
  'Owen O''Meara',
  'Aditri Phadtare',
  'Atticus Melbourne-Bianchi',
  'Disha Thirukumaran',
  'Aayush Sheth',
  'Ishika Tripathi',
  'Ananya Chamarti',
  'Ishaanvi Jain',
  'Om Khopade',
  'Taya Brodersen',
  'Reet Prasanna',
  'William Rackliffe',
  'Avani Ashwini',
  'Ansh Tolat',
  'Kapil Annadurai',
  'Archit Pothuganti',
  'Bhadra Rama',
  'Aniket Gupta',
  'Shine Lamichhane',
  'Aaliya Bothra',
  'Nikhil Zacharia',
  'Samarth Shinde',
  'Arham Shaha',
  'Ishi Parikh',
  'Rithikashri Puppala Vidhyadhar',
  'Shree Puvvadi',
  'Saanvi Gaikwad',
  'Shravan Vinodh Kumar',
  'Omkar Mohile',
  'Mayukh Shiven Algoti',
  'Farheen Mohamed',
  'Leah Tang',
  'Agasthya Vangara',
  'Vela Muthupandian',
  'Maahir Dholakia',
  'Sanjitha Bethanaboina',
  'Chetan Veeramachaneni',
  'Vaibhav Aljapur',
  'Nidhi Sivashankar',
  'Meenakshi Nair',
  'Kartavya Hirani',
  'Charani Veeramachaneni',
  'Saharsh Uyyala',
  'Armaan Agarwal',
  'Pooja Upadhyay',
  'Nissi Bandila',
  'Rayansh Kathoju',
  'Annette Jacob',
  'Nehan Abbu',
  'Mithra Venugopal',
  'Rami Ouahbi',
  'Mahija Monangi',
  'Colin Schwarting',
  'Mariia Demina',
  'Simran Chirayil',
  'Andrew Rice',
  'Benjamin Campbell',
  'Vedhanshi Kancherla',
  'Apaarpreet Bajaj',
  'Sai Muppalla',
  'Zander Albright',
  'Jacobi Phrommavath',
  'Niranjani Acharya',
  'Advait Cheruku',
  'Krish Patel',
  'Didhvika Alamuri',
  'Smriti Balaji',
  'Akaash Deepak',
  'Ella Kirby',
  'Naga Talasila',
  'Bhavesh Prakash',
  'Ashwinbabu Dhineshbabu',
  'Rakshaa Desikan',
  'Ayushi Amin',
  'Arnav Muley',
  'Diyamikaa Subramani',
  'Arjun Srivastava',
  'Spoorthi Pallamreddy',
  'Eshan Ahmed',
  'Nirvaan Bansal',
  'Betsy Sarabia',
  'Arav Surti',
  'Siddharth Kaligotla',
  'Bihani Sigdel',
  'Ishaan Gali',
  'Divya Ghosh',
  'Samriddhi Sangroula',
  'Tatiana Flowers',
  'Ashika Peruri',
  'Akansha Singh',
  'Luke Kim',
  'Oviya Sri Vasantha Kumar',
  'Anika Dukle',
  'Ansh Madhvani',
  'Srihitha Bogadapati',
  'Manogna Reddy (Sonu) Bhimreddy',
  'Siyona Varshney',
  'Leyao Xiong',
  'Akshataa Vijay Kumar',
  'Nikash Kamalnath',
  'Guru Jyothiraditya Punugupati',
  'Aneeshwar Rajesh',
  'Siddhanth Chandan',
  'Kishore Vasantha Kumar',
  'Reshitha Suresh',
  'Soham Jagdale',
  'Anwita Verma',
  'Dhruv Agarwal',
  'Ishan Das',
  'Jahnavi Pandiyaraj',
  'Aarav Singh',
  'Shivansh Gupta',
  'Haritha Nishali Sridhar',
  'Jinita Bhatta',
  'Skyler Ma',
  'Nandana Kar',
  'Arnav Sharma',
  'Lakshya Bullee',
  'Riya Aljapur',
  'Shrihan Bodla',
  'Lorenzo Bailey',
  'Nikhil Tadepalli',
  'Aayush Bhasuru',
  'Arnav Verma',
  'Ronit Sharma',
  'Vera Yao',
  'Naisha Verma',
  'Riya Parmar',
  'Anushka Menon',
  'Pranav Kuchibhotla',
  'Saanvi Chowla',
  'Rohan Kosaraju',
  'Amogh Dasture',
  'Aditi Mishra',
  'Farhan Hanif Haroon Rashedu',
  'Amen Qasim',
  'Vivian Ravi John',
  'Saanvi Jain',
  'Nissim Kale',
  'Advithasri Lakshmivaradaraj',
  'Krithik Reddy Adulla',
  'Cyrus Behra',
  'Nikhil Peddi',
  'Aryan Gupta',
  'Pramukh Chedella',
  'Vanshi Maladwala',
  'Camilla Kyle',
  'Saanvi Agarwal',
  'Amrithvarshan Anand',
  'Sneha Sawant',
  'Shruthi Appani',
  'Riya Mallampati',
  'Siri Joshi',
  'Aadi Patel',
  'Harshini Keshavamurthy',
  'Shalin Digra',
  'Pranav Pothula',
  'Manav Khanna',
  'Thomas Dixon',
  'Abhinav Basava',
  'Aanya Verma',
  'Pratyush Hesi',
  'Alex Gao',
  'Diya Nilekar',
  'Riva Tripathy',
  'Rajasri Kakaraparthi',
  'Aashna Reddy Nalamada',
  'Simar Sapra',
  'Sarvitha Saravanakannan',
  'Anjana Hari',
  'Ojas Vashisht',
  'Ashritha Kotha',
  'Veer Nitin Patel',
  'Subham Neupane',
  'Rohit Dodda',
  'João d''Amorim',
  'Aaditi Tiwari',
  'Olivia Varghese',
  'Rohen Trivedi',
  'Saharsha Ganjam',
  'Parth Patel',
  'Raj Patel',
  'Adithya Gottimukkala',
  'Hadi Niazi',
  'Neeraj Sivashankar',
  'Ishaan Gautam',
  'Amelia Bromirski',
  'Naisha Saxena',
  'Andrea Stouder'
);

-- Verify the counts
SELECT
  present,
  COUNT(*) as count
FROM "User"
GROUP BY present
ORDER BY present DESC;
